spring.application.name=paciente-service

server.port=8001
# Apunta al servidor Eureka que cree
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

